# Site settings
author: Steven Riggs
title: Flatiron Blog
header-img: img/home-bg.png
email: sfriggs21@gmail.com
copyright_name: Steven Riggs
description: > # this means to ignore newlines until "baseurl:"
  Assigned blog posts for Software Engineering course
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  StevenDRiggs

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
